# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1cd81e394c6dd8c8fe350e8076d288988d64f81e9cacf336af9138141982a04fe790278a3e7972ab59ac93db71ad320e2251b1b6fb8c841ff6ac5c10da5a6bc

test:
  secret_key_base: c7604e50d270ff18fb7c3659041531638ceed58dbe0ae936f69eea914efe6bed938225a70ed06d9d56244db8fd7bbd2ec8b1d9cd29177c9ca579e21b877699bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
